#line 1 "/Users/luke/Desktop/PL0-Compiler/src/aassembler/aassembler.cpp"

#line 3 "/Users/luke/Desktop/PL0-Compiler/src/aassembler/aassembler.cpp"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
typedef uint64_t flex_uint64_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, yy_size_t len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (yy_size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 37
#define YY_END_OF_BUFFER 38
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_acclist[116] =
    {   0,
       38,   37,   36,   37,   37,   37,   33,   35,   36,   37,
       37,   37,   37,16386,   37,16386,   37,16387,   37,16387,
       37,    1,   37,   35,   32,   33,   35,   33,   35, 8194,
    16386, 8194,   35,16386, 8195,16387, 8195,   35,16387,    1,
       32,   35, 8194,   32,   35, 8195,   32,   35,    4,   35,
        9,   35,16403,    7,   35,   25,   35,16402,    8,   35,
        5,   35,16415,   27,   35,16412,    6,   35,   17,   35,
       26,   35,   10,   35,   14,   35,   15,   35,   12,   35,
       13,   35,   11,   35, 8211,   35, 8210,   35,16413,16404,
    16405,   23,   35,   16,   35, 8223,   35, 8220,   35,16414,

       34,   35,16406,   24,   35, 8221,   35, 8212,   35, 8213,
       35, 8222,   35, 8214,   35
    } ;

static const flex_int16_t yy_accept[286] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        3,    5,    6,    7,   11,   12,   13,   15,   17,   19,
       21,   22,   24,   24,   25,   25,   28,   28,   28,   28,
       28,   28,   28,   28,   28,   28,   28,   28,   28,   28,
       30,   30,   30,   30,   31,   31,   32,   32,   34,   34,
       35,   35,   36,   36,   37,   37,   39,   39,   40,   40,
       41,   41,   41,   41,   41,   41,   41,   41,   41,   41,
       41,   41,   41,   41,   41,   41,   41,   41,   41,   41,
       41,   41,   43,   43,   43,   43,   46,   46,   46,   46,
       46,   49,   49,   49,   49,   49,   49,   49,   49,   49,

       49,   49,   49,   49,   49,   49,   49,   49,   49,   49,
       49,   49,   49,   49,   49,   49,   49,   49,   51,   51,
       51,   51,   53,   53,   53,   53,   53,   53,   54,   54,
       56,   56,   56,   56,   58,   58,   59,   59,   59,   59,
       61,   61,   61,   61,   61,   61,   61,   61,   63,   63,
       63,   63,   63,   64,   64,   64,   64,   64,   64,   64,
       64,   64,   64,   64,   66,   66,   66,   66,   67,   67,
       67,   67,   67,   67,   67,   67,   69,   69,   69,   71,
       71,   71,   71,   71,   71,   73,   73,   73,   73,   73,
       75,   75,   75,   77,   77,   77,   79,   79,   79,   81,

       81,   81,   83,   83,   83,   85,   85,   85,   87,   87,
       87,   87,   89,   89,   89,   89,   90,   91,   92,   92,
       94,   94,   94,   94,   94,   94,   94,   94,   94,   96,
       96,   96,   98,   98,   98,   98,   98,   98,   98,   98,
       98,   98,   98,  100,  100,  101,  101,  101,  101,  101,
      101,  103,  103,  104,  104,  106,  106,  106,  106,  106,
      106,  106,  108,  108,  108,  110,  110,  110,  112,  112,
      112,  112,  112,  112,  114,  114,  114,  114,  114,  114,
      116,  116,  116,  116,  116
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    1,    4,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    1,    1,    1,
        1,    1,    1,    1,    6,    7,    8,    9,   10,   11,
       12,   13,   14,   15,   11,   16,   17,   18,   19,   20,
       21,   22,   23,   24,   25,   26,   27,   11,   11,   28,
        1,    1,    1,    1,   11,    1,   29,   30,   31,   32,

       33,   11,   34,   35,   36,   37,   11,   38,   39,   40,
       41,   42,   43,   44,   45,   46,   47,   48,   49,   11,
       11,   50,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[51] =
    {   0,
        1,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2
    } ;

static const flex_int16_t yy_base[337] =
    {   0,
      724,    0,    2,    7,   12,   16,  723,  722,  724,  728,
      728,  720,   19,  728,  719,   28,   67,   72,   36,   77,
      718,  728,  717,  728,    0,  728,  716,   51,   79,  116,
       44,   40,   83,   86,   87,   88,   85,   23,  715,  728,
       91,  141,   97,  728,  714,  151,  113,  728,  713,  163,
      133,  728,  712,  144,  155,  728,  711,  168,  710,  728,
      709,  170,  158,   21,  120,  172,  173,  110,  174,  175,
      178,  179,  181,  184,  185,  183,  190,  194,  208,  212,
      216,  728,  708,  707,  230,  728,  706,  705,  704,  236,
      728,  703,  702,  239,  207,  247,  249,   50,  251,  227,

      254,  101,  243,  259,  268,  257,  271,  275,  241,  273,
      290,  276,  274,  701,  700,  699,  297,  728,  698,  189,
      302,  728,  697,  287,  299,  309,  311,  308,  322,  728,
      696,  325,  332,  728,  695,  335,  313,  343,  345,  728,
      694,  354,  357,  365,  340,  361,  373,  728,  693,  376,
      379,  692,  389,  691,  393,  396,  399,  402,  405,  411,
      414,  690,  418,  728,  689,  688,  421,  426,  382,  233,
      370,  431,  433,  687,  436,  728,  686,  439,  728,  685,
      428,  441,  684,  445,  728,  683,  448,  452,  455,  728,
      682,  458,  728,  681,  463,  728,  680,  467,  728,  679,

      470,  728,  678,  473,  728,  677,  476,  728,  676,  675,
      479,  728,  674,  486,  489,  492,  495,  499,  503,  728,
      673,  543,  500,  506,  509,  511,  496,  514,  728,  481,
      517,  728,  442,  408,  383,  380,  378,  367,  351,  349,
      347,  520,  728,  336,  524,  528,  531,  535,  319,  539,
      728,  294,  542,  546,  728,  283,  277,  261,  225,  550,
      553,  728,  222,  556,  728,  201,  559,  728,  195,  147,
      562,  136,  566,  728,  122,  119,  117,  104,  569,  728,
       94,   58,   46,  728,  573,  575,  577,  579,  581,  583,
      585,  587,    4,  589,  591,  593,  595,  597,  599,  601,

      603,  605,  607,  609,  611,  613,  615,  617,  619,  621,
      623,  625,  627,  629,  631,  633,  635,  637,  639,  641,
      643,  645,  647,  649,  651,  653,  655,  657,  659,  661,
      663,  665,  667,  669,  671,  673
    } ;

static const flex_int16_t yy_def[337] =
    {   0,
      285,  286,  285,  286,  287,  288,  289,  289,  284,  284,
      284,  290,  290,  284,  291,  292,  284,  292,  293,  294,
      295,  284,  290,  284,   13,  284,  296,  290,  290,  290,
      290,  290,  290,  290,  290,  290,  290,  290,  291,  284,
       13,  292,  284,  284,  297,  284,   13,  284,  298,  292,
      284,  284,  299,  293,   13,  284,  300,  294,  295,  284,
      296,  290,  290,  290,  290,  290,  290,  290,  290,  290,
      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,
       13,  284,  301,  297,   13,  284,  302,  298,  299,   13,
      284,  303,  300,  290,  290,  290,  290,  290,  290,  290,

      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,
      290,  290,  290,  301,  302,  303,  290,  284,  304,  290,
      290,  284,  305,  290,  290,  290,  290,  290,  290,  284,
      306,  290,  290,  284,  307,  290,  290,  290,  290,  284,
      308,  290,  290,  290,  290,  290,  290,  284,  309,  290,
      290,  304,  310,  305,  290,  290,  290,  290,  290,  290,
      290,  306,  290,  284,  311,  307,  290,  312,  290,  290,
      290,  290,  290,  308,  290,  284,  313,  290,  284,  314,
      290,  290,  309,  290,  284,  315,  290,  310,  290,  284,
      316,  290,  284,  317,  290,  284,  318,  290,  284,  319,

      290,  284,  320,  290,  284,  321,  290,  284,  322,  311,
      290,  284,  323,  312,  290,  324,  290,  290,  290,  284,
      325,  313,  314,  290,  290,  290,  315,  290,  284,  326,
      290,  284,  327,  316,  317,  318,  319,  320,  321,  322,
      323,  290,  284,  328,  329,  324,  290,  290,  325,  290,
      284,  330,  290,  290,  284,  331,  326,  327,  328,  329,
      290,  284,  332,  290,  284,  333,  290,  284,  334,  330,
      290,  331,  290,  284,  335,  332,  333,  334,  290,  284,
      336,  335,  336,    0,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,

      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284
    } ;

static const flex_int16_t yy_nxt[779] =
    {   0,
       12,   13,   14,   15,   11,   54,   17,   12,   13,   14,
       15,   18,   10,   10,   11,   10,   12,   13,   14,   15,
       25,   26,   27,   24,   28,   24,   29,   30,   23,   41,
       24,   23,   31,   32,   33,   34,   35,   51,   52,   53,
       36,   37,   24,   96,   80,   38,   24,   28,  280,   29,
       30,  128,   24,   24,   31,   32,   33,   34,   35,   62,
      274,   70,   36,   37,   71,   96,   80,   38,   43,   44,
       45,   46,   23,   47,   48,   49,   50,   23,   55,   56,
       57,   24,   62,   70,   63,   24,   71,   24,   24,   24,
       24,   64,   81,   82,   83,   65,  280,   76,   43,   44,

       45,   72,  136,   24,   73,   75,  268,   63,   77,   78,
       74,   79,   24,   64,   85,   86,   87,   65,   24,  265,
       76,  262,   24,   72,  274,   66,   73,   75,  100,   67,
       77,   78,   74,   79,   51,   52,   53,   68,  255,   97,
       69,   23,   41,   24,   23,   51,   52,   53,   66,  251,
      100,   67,   43,   44,   45,   46,   90,   91,   92,   68,
       24,   97,   69,   23,   47,   48,   49,   50,   23,   55,
       56,   57,   24,   95,   24,   24,   24,   24,   94,   98,
       24,   24,  102,   24,  104,   24,   24,   24,  108,  105,
      153,   24,   24,  101,  103,   95,   24,  268,   99,  106,

      111,   94,   98,  265,  107,  102,  109,  104,  110,   24,
       24,  108,  105,  112,   24,  101,  103,   81,   82,   83,
       99,  106,  120,  111,  262,  113,  107,  243,  109,   24,
      110,   85,   86,   87,  216,   24,  112,   90,   91,   92,
      117,  118,  119,   24,  120,   24,  132,  113,  121,  122,
      123,   24,  129,  130,  131,  133,  134,  135,  124,   24,
      125,   24,  137,  232,  126,  145,  127,  138,  132,  139,
      140,  141,  143,   82,   83,   24,   24,   24,   24,  229,
      142,  124,  125,  144,  137,  255,  126,  145,  127,   24,
      138,  147,  148,  149,  146,  150,  251,  151,  117,  118,

      119,   24,  142,  121,  122,  123,  144,  155,  156,  128,
       24,   24,  161,   24,  168,   24,  146,  150,  158,  151,
      160,  220,  157,  129,  130,  131,  163,  164,  165,  155,
      169,  156,  159,  133,  134,  135,  136,   24,  243,  167,
      170,  158,   24,  160,  157,   24,  139,  140,  141,  212,
      171,  208,  169,  205,  159,  175,  176,  177,  143,   82,
       83,  181,  170,   24,  172,  173,  178,  179,  180,  202,
      182,  217,   24,  171,  147,  148,  149,  184,  185,  186,
      199,   24,  196,  181,   24,  193,  172,  173,  187,   23,
      153,   24,   23,  182,  189,  190,  191,  192,  193,  194,

      195,  196,  197,  198,  199,  200,  201,  202,  203,  215,
      190,  187,  204,  205,  206,  207,  208,  209,  161,  163,
      164,  165,  211,  212,  213,  167,   23,  168,   24,   23,
       24,  215,  218,   24,  219,  220,  221,  175,  176,  177,
      178,  179,  180,   24,  232,  224,  184,  185,  186,  228,
      229,  230,   23,  231,  232,  233,  189,  190,  191,  192,
      193,  194,  225,  226,  195,  196,  197,  224,  198,  199,
      200,  201,  202,  203,  204,  205,  206,  207,  208,  209,
      211,  212,  213,  229,  225,  226,   23,  242,  243,  244,
      245,   24,   23,  216,   24,   23,  217,   24,  185,  247,

      218,   24,  179,  248,  219,  220,  221,  250,  251,  252,
      253,   24,  254,  255,  256,  228,  229,  230,  231,  232,
      233,  242,  243,  244,   23,  245,   24,   23,   23,  261,
      262,  263,  264,  265,  266,  247,  267,  268,  269,  248,
      250,  251,  252,  253,   24,  176,  271,  254,  255,  256,
       23,  273,  274,  275,  261,  262,  263,  264,  265,  266,
      267,  268,  269,  279,  280,  281,  271,  273,  274,  275,
      279,  280,  281,   10,   10,   16,   16,   19,   19,   20,
       20,   21,   21,   23,   23,   39,   39,   42,   42,   58,
       58,   59,   59,   61,   61,   84,   84,   88,   88,   89,

       89,   93,   93,  114,  114,  115,  115,  116,  116,  152,
      152,  154,  154,  162,  162,  166,  166,  174,  174,  183,
      183,  188,  188,  210,  210,  214,  214,  222,  222,  223,
      223,  227,  227,  234,  234,  235,  235,  236,  236,  237,
      237,  238,  238,  239,  239,  240,  240,  241,  241,  246,
      246,  249,  249,  257,  257,  258,  258,  259,  259,  260,
      260,  270,  270,  272,  272,  276,  276,  277,  277,  278,
      278,  282,  282,  283,  283,  220,  212,  164,  208,  205,
      202,  199,  196,  193,  190,  185,  148,  179,  176,  140,
      134,  164,  130,  122,  118,  148,  140,  134,  130,  122,

      118,   91,   86,   82,   56,   91,   52,   48,   86,   44,
       82,   26,   60,   56,   52,   48,   44,   40,   26,   24,
       60,   40,   24,  284,   22,   22,   11,    9,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284
    } ;

static const flex_int16_t yy_chk[779] =
    {   0,
        2,    2,    2,    2,    3,  293,    3,    4,    4,    4,
        4,    4,    5,    5,    5,    5,    6,    6,    6,    6,
       13,   13,   13,   64,   13,   38,   13,   13,   16,   16,
       16,   16,   13,   13,   13,   13,   13,   19,   19,   19,
       13,   13,   32,   64,   38,   13,   31,   13,  283,   13,
       13,   98,   98,   28,   13,   13,   13,   13,   13,   28,
      282,   31,   13,   13,   32,   64,   38,   13,   17,   17,
       17,   17,   18,   18,   18,   18,   18,   20,   20,   20,
       20,   29,   28,   31,   29,   33,   32,   37,   34,   35,
       36,   29,   41,   41,   41,   29,  281,   36,   43,   43,

       43,   33,  102,  102,   34,   35,  278,   29,   37,   37,
       34,   37,   68,   29,   47,   47,   47,   29,   30,  277,
       36,  276,   65,   33,  275,   30,   34,   35,   68,   30,
       37,   37,   34,   37,   51,   51,   51,   30,  272,   65,
       30,   42,   42,   42,   42,   54,   54,   54,   30,  270,
       68,   30,   46,   46,   46,   46,   55,   55,   55,   30,
       63,   65,   30,   50,   50,   50,   50,   50,   58,   58,
       58,   58,   62,   63,   66,   67,   69,   70,   62,   66,
       71,   72,   70,   73,   72,   76,   74,   75,   76,   73,
      120,  120,   77,   69,   71,   63,   78,  269,   67,   74,

       78,   62,   66,  266,   75,   70,   76,   72,   77,   95,
       79,   76,   73,   79,   80,   69,   71,   81,   81,   81,
       67,   74,   95,   78,  263,   80,   75,  259,   76,  100,
       77,   85,   85,   85,  170,  170,   79,   90,   90,   90,
       94,   94,   94,  109,   95,  103,  100,   80,   96,   96,
       96,   97,   99,   99,   99,  101,  101,  101,   97,  106,
       97,  104,  103,  258,   97,  109,   97,  104,  100,  105,
      105,  105,  107,  107,  107,  110,  113,  108,  112,  257,
      106,   97,   97,  108,  103,  256,   97,  109,   97,  124,
      104,  111,  111,  111,  110,  112,  252,  113,  117,  117,

      117,  125,  106,  121,  121,  121,  108,  124,  125,  128,
      128,  126,  128,  127,  137,  137,  110,  112,  126,  113,
      127,  249,  125,  129,  129,  129,  132,  132,  132,  124,
      137,  125,  126,  133,  133,  133,  136,  136,  244,  136,
      137,  126,  145,  127,  125,  138,  139,  139,  139,  241,
      138,  240,  137,  239,  126,  142,  142,  142,  143,  143,
      143,  145,  137,  146,  138,  138,  144,  144,  144,  238,
      146,  171,  171,  138,  147,  147,  147,  150,  150,  150,
      237,  151,  236,  145,  169,  235,  138,  138,  151,  153,
      153,  153,  153,  146,  155,  155,  155,  156,  156,  156,

      157,  157,  157,  158,  158,  158,  159,  159,  159,  169,
      234,  151,  160,  160,  160,  161,  161,  161,  161,  163,
      163,  163,  167,  167,  167,  167,  168,  168,  168,  168,
      181,  169,  172,  172,  173,  173,  173,  175,  175,  175,
      178,  178,  178,  182,  233,  181,  184,  184,  184,  187,
      187,  187,  188,  188,  188,  188,  189,  189,  189,  192,
      192,  192,  182,  182,  195,  195,  195,  181,  198,  198,
      198,  201,  201,  201,  204,  204,  204,  207,  207,  207,
      211,  211,  211,  230,  182,  182,  214,  214,  214,  214,
      215,  215,  216,  216,  216,  216,  217,  217,  227,  217,

      218,  218,  223,  218,  219,  219,  219,  224,  224,  224,
      225,  225,  226,  226,  226,  228,  228,  228,  231,  231,
      231,  242,  242,  242,  245,  245,  245,  245,  246,  246,
      246,  246,  247,  247,  247,  247,  248,  248,  248,  248,
      250,  250,  250,  253,  253,  222,  253,  254,  254,  254,
      260,  260,  260,  260,  261,  261,  261,  264,  264,  264,
      267,  267,  267,  271,  271,  271,  271,  273,  273,  273,
      279,  279,  279,  285,  285,  286,  286,  287,  287,  288,
      288,  289,  289,  290,  290,  291,  291,  292,  292,  294,
      294,  295,  295,  296,  296,  297,  297,  298,  298,  299,

      299,  300,  300,  301,  301,  302,  302,  303,  303,  304,
      304,  305,  305,  306,  306,  307,  307,  308,  308,  309,
      309,  310,  310,  311,  311,  312,  312,  313,  313,  314,
      314,  315,  315,  316,  316,  317,  317,  318,  318,  319,
      319,  320,  320,  321,  321,  322,  322,  323,  323,  324,
      324,  325,  325,  326,  326,  327,  327,  328,  328,  329,
      329,  330,  330,  331,  331,  332,  332,  333,  333,  334,
      334,  335,  335,  336,  336,  221,  213,  210,  209,  206,
      203,  200,  197,  194,  191,  186,  183,  180,  177,  174,
      166,  165,  162,  154,  152,  149,  141,  135,  131,  123,

      119,  116,  115,  114,   93,   92,   89,   88,   87,   84,
       83,   61,   59,   57,   53,   49,   45,   39,   27,   23,
       21,   15,   12,    9,    8,    7,    1,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284
    } ;

extern int yy_flex_debug;
int yy_flex_debug = 0;

static yy_state_type *yy_state_buf=0, *yy_state_ptr=0;
static char *yy_full_match;
static int yy_lp;
static int yy_looking_for_trail_begin = 0;
static int yy_full_lp;
static int *yy_full_state;
#define YY_TRAILING_MASK 0x2000
#define YY_TRAILING_HEAD_MASK 0x4000
#define REJECT \
{ \
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */ \
yy_cp = (yy_full_match); /* restore poss. backed-over text */ \
(yy_lp) = (yy_full_lp); /* restore orig. accepting pos. */ \
(yy_state_ptr) = (yy_full_state); /* restore orig. state */ \
yy_current_state = *(yy_state_ptr); /* restore curr. state */ \
++(yy_lp); \
goto find_rule; \
}

#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "aassembler.l"
#line 2 "aassembler.l"
	#include <string>
	#include <map>
	#include <iostream>
	#include "opcodes.hpp"
	using namespace std;
	int tmp, error = 0;

	void emit(int, int = 0);
	FILE * f_bin, * f_json;
	using namespace std;
	map<string,int> label;
#line 757 "/Users/luke/Desktop/PL0-Compiler/src/aassembler/aassembler.cpp"

#line 759 "/Users/luke/Desktop/PL0-Compiler/src/aassembler/aassembler.cpp"

#define INITIAL 0
#define INT 1
#define LABEL 2
#define REST 3

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			yy_size_t yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		yy_size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

        /* Create the reject buffer large enough to save one state per allowed character. */
        if ( ! (yy_state_buf) )
            (yy_state_buf) = (yy_state_type *)yyalloc(YY_STATE_BUF_SIZE  );
            if ( ! (yy_state_buf) )
                YY_FATAL_ERROR( "out of dynamic memory in yylex()" );

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 22 "aassembler.l"

#line 990 "/Users/luke/Desktop/PL0-Compiler/src/aassembler/aassembler.cpp"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();

		(yy_state_ptr) = (yy_state_buf);
		*(yy_state_ptr)++ = yy_current_state;

yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 285 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			*(yy_state_ptr)++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 728 );

yy_find_action:
		yy_current_state = *--(yy_state_ptr);
		(yy_lp) = yy_accept[yy_current_state];
goto find_rule; /* Shut up GCC warning -Wall */
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( (yy_lp) && (yy_lp) < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[(yy_lp)];
				if ( yy_act & YY_TRAILING_HEAD_MASK ||
				     (yy_looking_for_trail_begin) )
					{
					if ( yy_act == (yy_looking_for_trail_begin) )
						{
						(yy_looking_for_trail_begin) = 0;
						yy_act &= ~YY_TRAILING_HEAD_MASK;
						break;
						}
					}
				else if ( yy_act & YY_TRAILING_MASK )
					{
					(yy_looking_for_trail_begin) = yy_act & ~YY_TRAILING_MASK;
					(yy_looking_for_trail_begin) |= YY_TRAILING_HEAD_MASK;
					}
				else
					{
					(yy_full_match) = yy_cp;
					(yy_full_state) = (yy_state_ptr);
					(yy_full_lp) = (yy_lp);
					break;
					}
				++(yy_lp);
				goto find_rule;
				}
			--yy_cp;
			yy_current_state = *--(yy_state_ptr);
			(yy_lp) = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 23 "aassembler.l"
BEGIN 0;
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 24 "aassembler.l"
emit(tmp, atoi(yytext)); BEGIN REST;
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 25 "aassembler.l"
{
	if (label.find(string(yytext)) == label.end()) {
		error = -1;
		cout << "Undefined label '" << yytext << " " << error << "'\n";
	}
	emit(tmp, label[yytext]); BEGIN REST;
}
	YY_BREAK
case 4:
/* rule 4 can match eol */
YY_RULE_SETUP
#line 32 "aassembler.l"
emit(c_op_add);
	YY_BREAK
case 5:
/* rule 5 can match eol */
YY_RULE_SETUP
#line 33 "aassembler.l"
emit(c_op_sub);
	YY_BREAK
case 6:
/* rule 6 can match eol */
YY_RULE_SETUP
#line 34 "aassembler.l"
emit(c_op_mult);
	YY_BREAK
case 7:
/* rule 7 can match eol */
YY_RULE_SETUP
#line 35 "aassembler.l"
emit(c_op_div);
	YY_BREAK
case 8:
/* rule 8 can match eol */
YY_RULE_SETUP
#line 36 "aassembler.l"
emit(c_op_mod);
	YY_BREAK
case 9:
/* rule 9 can match eol */
YY_RULE_SETUP
#line 37 "aassembler.l"
emit(c_op_chs);
	YY_BREAK
case 10:
/* rule 10 can match eol */
YY_RULE_SETUP
#line 38 "aassembler.l"
emit(c_op_cmpeq);
	YY_BREAK
case 11:
/* rule 11 can match eol */
YY_RULE_SETUP
#line 39 "aassembler.l"
emit(c_op_cmpne);
	YY_BREAK
case 12:
/* rule 12 can match eol */
YY_RULE_SETUP
#line 40 "aassembler.l"
emit(c_op_cmple);
	YY_BREAK
case 13:
/* rule 13 can match eol */
YY_RULE_SETUP
#line 41 "aassembler.l"
emit(c_op_cmplt);
	YY_BREAK
case 14:
/* rule 14 can match eol */
YY_RULE_SETUP
#line 42 "aassembler.l"
emit(c_op_cmpge);
	YY_BREAK
case 15:
/* rule 15 can match eol */
YY_RULE_SETUP
#line 43 "aassembler.l"
emit(c_op_cmpgt);
	YY_BREAK
case 16:
/* rule 16 can match eol */
YY_RULE_SETUP
#line 44 "aassembler.l"
emit(c_write);
	YY_BREAK
case 17:
/* rule 17 can match eol */
YY_RULE_SETUP
#line 45 "aassembler.l"
emit(c_read);
	YY_BREAK
case 18:
/* rule 18 can match eol */
YY_RULE_SETUP
#line 46 "aassembler.l"
tmp = c_inc; BEGIN INT;
	YY_BREAK
case 19:
/* rule 19 can match eol */
YY_RULE_SETUP
#line 47 "aassembler.l"
tmp = c_dec; BEGIN INT;
	YY_BREAK
case 20:
/* rule 20 can match eol */
YY_RULE_SETUP
#line 48 "aassembler.l"
tmp = c_loadc; BEGIN INT;
	YY_BREAK
case 21:
/* rule 21 can match eol */
YY_RULE_SETUP
#line 49 "aassembler.l"
tmp = c_loadr; BEGIN INT;
	YY_BREAK
case 22:
/* rule 22 can match eol */
YY_RULE_SETUP
#line 50 "aassembler.l"
tmp = c_storer; BEGIN INT;
	YY_BREAK
case 23:
/* rule 23 can match eol */
YY_RULE_SETUP
#line 51 "aassembler.l"
emit(c_loads);
	YY_BREAK
case 24:
/* rule 24 can match eol */
YY_RULE_SETUP
#line 52 "aassembler.l"
emit(c_stores);
	YY_BREAK
case 25:
/* rule 25 can match eol */
YY_RULE_SETUP
#line 53 "aassembler.l"
emit(c_dup);
	YY_BREAK
case 26:
/* rule 26 can match eol */
YY_RULE_SETUP
#line 54 "aassembler.l"
emit(c_swap);
	YY_BREAK
case 27:
/* rule 27 can match eol */
YY_RULE_SETUP
#line 55 "aassembler.l"
emit(c_drop);
	YY_BREAK
case 28:
/* rule 28 can match eol */
YY_RULE_SETUP
#line 56 "aassembler.l"
tmp = c_jump; BEGIN LABEL;
	YY_BREAK
case 29:
/* rule 29 can match eol */
YY_RULE_SETUP
#line 57 "aassembler.l"
tmp = c_jumpz; BEGIN LABEL;
	YY_BREAK
case 30:
/* rule 30 can match eol */
YY_RULE_SETUP
#line 58 "aassembler.l"
tmp = c_jumpnz; BEGIN LABEL;
	YY_BREAK
case 31:
/* rule 31 can match eol */
YY_RULE_SETUP
#line 59 "aassembler.l"
tmp = c_call; BEGIN LABEL;
	YY_BREAK
case 32:
/* rule 32 can match eol */
YY_RULE_SETUP
#line 60 "aassembler.l"
emit(c_nop, 0);
	YY_BREAK
case 33:
/* rule 33 can match eol */
YY_RULE_SETUP
#line 61 "aassembler.l"
emit(c_nop, 0);
	YY_BREAK
case 34:
/* rule 34 can match eol */
YY_RULE_SETUP
#line 62 "aassembler.l"
emit(c_return);
	YY_BREAK
case 35:
/* rule 35 can match eol */
YY_RULE_SETUP
#line 63 "aassembler.l"
cout << "KO: '" << yytext << "'\n"; error = -2;
	YY_BREAK
case 36:
/* rule 36 can match eol */
YY_RULE_SETUP
#line 64 "aassembler.l"
cout << "NL?!?!?!\n"; error = -3;;
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 65 "aassembler.l"
ECHO;
	YY_BREAK
#line 1299 "/Users/luke/Desktop/PL0-Compiler/src/aassembler/aassembler.cpp"
			case YY_STATE_EOF(INITIAL):
			case YY_STATE_EOF(INT):
			case YY_STATE_EOF(LABEL):
			case YY_STATE_EOF(REST):
				yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	(yy_state_ptr) = (yy_state_buf);
	*(yy_state_ptr)++ = yy_current_state;

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 285 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		*(yy_state_ptr)++ = yy_current_state;
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    
	YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 285 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 284);
	if ( ! yy_is_jam )
		*(yy_state_ptr)++ = yy_current_state;

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		yy_size_t number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        yy_size_t yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

    (yy_state_buf) = 0;
    (yy_state_ptr) = 0;
    (yy_full_match) = 0;
    (yy_lp) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    yyfree ( (yy_state_buf) );
    (yy_state_buf)  = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 65 "aassembler.l"

int main (int argc, char * argv[]) {
	string filename;
	char line[100], l[20];
	int lnr = 0;

	if (argc != 2) {
		cout << "No asm-file specified" << endl;
		return -4;
	}
	filename = string(argv[argc - 1]);
	if (filename.length() > 4  && filename.substr(filename.length() - 4) == ".asm")
		filename = filename.substr(0, filename.length() - 4);

	if ((yyin = fopen((filename + ".asm").c_str(), "r")) == NULL) {
		cout << "Unable to open '" << filename << "'" << endl;
		return -4;
	}

	while (fgets(line, 100, yyin) != NULL) {
		if (line[0] > ' ') {
			sscanf(line, "%s", l);
			if (label.find(string(l)) == label.end())
				label[l] = lnr;
			else {
				cout << "Duplicate label '" << l << "' at lnr " << lnr << endl;
				error = -1;
			}
		}
		lnr++;
	}
	if (error)
		return error;

	rewind(yyin);
	f_bin = fopen((filename + ".bin").c_str(), "w");
	f_json = fopen((filename + ".json").c_str(), "w");
	fprintf(f_json,"[");
	yylex();
	fprintf(f_json,"\n]\n");
	fclose(f_bin);
	fclose(f_json);
	return error;
}

void emit(int c, int a) {
	static int lnr;
	#ifdef AASSEMBLER_OUTPUT
		printf("%03d %4d %4d\n", lnr, c, a);
	#endif
	fprintf(f_json, "%s[\"%s\",%d]", lnr?",\n\t":"\n\t", opct[c], a);
	fwrite(&c, sizeof(c), 1, f_bin);
	fwrite(&a, sizeof(a), 1, f_bin);
	lnr++;
}
int yywrap() {
	return 1;
}
